/**
 * Token build script — generates dist/tokens.css and dist/tokens.json
 * from the TypeScript source of truth.
 *
 * Run: pnpm --filter @careerops/tokens build
 */

import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { teal, gold, neutral } from './src/colors.js';
import { lightTokens, darkTokens } from './src/semantic.js';
import { spacing, radii, zIndex } from './src/spacing.js';
import { fontFamily, fontWeight, fontSize, lineHeight, letterSpacing } from './src/typography.js';
import { easings, durations } from './src/motion.js';
import { shadowsLight, shadowsDark } from './src/shadows.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const distDir = join(__dirname, 'dist');

if (!existsSync(distDir)) {
  mkdirSync(distDir, { recursive: true });
}

// ─── CSS variables ─────────────────────────────────────────────────────────

const kebab = (s: string): string => s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

const semanticToCSS = (tokens: typeof lightTokens, indent = '  '): string =>
  Object.entries(tokens)
    .map(([key, value]) => `${indent}--${kebab(key)}: ${value};`)
    .join('\n');

const rampToCSS = (name: string, ramp: Record<string, string>, indent = '  '): string =>
  Object.entries(ramp)
    .map(([step, value]) => `${indent}--${name}-${step}: ${value};`)
    .join('\n');

const spacingToCSS = (indent = '  '): string =>
  Object.entries(spacing)
    .map(([key, value]) => `${indent}--space-${key}: ${value};`)
    .join('\n');

const radiiToCSS = (indent = '  '): string =>
  Object.entries(radii)
    .map(([key, value]) => `${indent}--radius-${key}: ${value};`)
    .join('\n');

const zIndexToCSS = (indent = '  '): string =>
  Object.entries(zIndex)
    .map(([key, value]) => `${indent}--z-${key}: ${value};`)
    .join('\n');

const fontFamilyToCSS = (indent = '  '): string =>
  Object.entries(fontFamily)
    .map(([key, value]) => `${indent}--font-${key}: ${value};`)
    .join('\n');

const fontSizeToCSS = (indent = '  '): string =>
  Object.entries(fontSize)
    .map(([key, value]) => `${indent}--text-${key}: ${value};`)
    .join('\n');

const lineHeightToCSS = (indent = '  '): string =>
  Object.entries(lineHeight)
    .map(([key, value]) => `${indent}--lh-${key}: ${value};`)
    .join('\n');

const letterSpacingToCSS = (indent = '  '): string =>
  Object.entries(letterSpacing)
    .map(([key, value]) => `${indent}--tracking-${key}: ${value};`)
    .join('\n');

const fontWeightToCSS = (indent = '  '): string =>
  Object.entries(fontWeight)
    .map(([key, value]) => `${indent}--weight-${key}: ${value};`)
    .join('\n');

const easingsToCSS = (indent = '  '): string =>
  Object.entries(easings)
    .map(([key, value]) => `${indent}--ease-${key}: ${value};`)
    .join('\n');

const durationsToCSS = (indent = '  '): string =>
  Object.entries(durations)
    .map(([key, value]) => `${indent}--duration-${key}: ${value}ms;`)
    .join('\n');

const shadowsToCSS = (shadows: typeof shadowsLight, indent = '  '): string =>
  Object.entries(shadows)
    .map(([key, value]) => `${indent}--shadow-${kebab(key)}: ${value};`)
    .join('\n');

const css = `/**
 * Generated by @careerops/tokens — do not edit by hand.
 * Source: packages/tokens/src/*.ts
 */

:root {
  /* Color ramps */
${rampToCSS('teal', teal)}
${rampToCSS('gold', gold)}
${rampToCSS('neutral', neutral)}

  /* Spacing + radii + z-index */
${spacingToCSS()}
${radiiToCSS()}
${zIndexToCSS()}

  /* Typography */
${fontFamilyToCSS()}
${fontWeightToCSS()}
${fontSizeToCSS()}
${lineHeightToCSS()}
${letterSpacingToCSS()}

  /* Motion */
${easingsToCSS()}
${durationsToCSS()}

  /* Semantic tokens — light mode (default) */
${semanticToCSS(lightTokens)}
${shadowsToCSS(shadowsLight)}
}

[data-theme='dark'] {
${semanticToCSS(darkTokens)}
${shadowsToCSS(shadowsDark)}
}

/* Honor user preference at the system level when no explicit theme is set */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${semanticToCSS(darkTokens)}
${shadowsToCSS(shadowsDark)}
  }
}
`;

writeFileSync(join(distDir, 'tokens.css'), css, 'utf8');

// ─── JSON ──────────────────────────────────────────────────────────────────

const json = {
  ramps: { teal, gold, neutral },
  semantic: { light: lightTokens, dark: darkTokens },
  spacing,
  radii,
  zIndex,
  fontFamily,
  fontWeight,
  fontSize,
  lineHeight,
  letterSpacing,
  easings,
  durations,
  shadows: { light: shadowsLight, dark: shadowsDark },
};

writeFileSync(join(distDir, 'tokens.json'), JSON.stringify(json, null, 2), 'utf8');

// ─── done ──────────────────────────────────────────────────────────────────

console.log('✓ tokens.css written');
console.log('✓ tokens.json written');
